"""empty message

Revision ID: ffba63a26dbc
Revises: 
Create Date: 2023-12-08 20:53:43.271149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffba63a26dbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('description', sa.VARCHAR(length=200), nullable=True))
    op.add_column('items', sa.Column('type', sa.VARCHAR(), nullable=False))
    op.add_column('items', sa.Column('abilities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('equipment', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'equipment')
    op.drop_column('items', 'abilities')
    op.drop_column('items', 'type')
    op.drop_column('items', 'description')
    op.drop_table('cores')
    # ### end Alembic commands ###
